### ISSUE TITLE
Error when loading tokenizers gem

### ISSUE THREAD

**Issue by crohr** [ankane/tokenizers-ruby#31]
Using ruby:3.2.2 docker image:

```
$ bin/bundle
[...]
Installing tokenizers 0.4.0 (x86_64-linux)
Bundle complete! 17 Gemfile dependencies, 77 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

Launching a rails console fails with:
```
$ bin/rails c
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Exception(#<NameError: uninitialized constant Tokenizers>))', ext/tokenizers/src/lib.rs:25:97
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
<internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require': called `Result::unwrap()` on an `Err` value: Error(Exception(#<NameError: uninitialized constant Tokenizers>)) (fatal)
        from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /usr/local/bundle/gems/tokenizers-0.4.0-x86_64-linux/lib/tokenizers.rb:3:in `<top (required)>'
        from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/runtime.rb:60:in `require'
        from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/runtime.rb:55:in `each'
        from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/runtime.rb:55:in `block in require'
        from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/runtime.rb:44:in `each'
        from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler/runtime.rb:44:in `require'
        from /usr/local/bundle/gems/bundler-2.4.10/lib/bundler.rb:196:in `require'
        from /usr/src/app/config/application.rb:7:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /usr/local/bundle/gems/railties-7.0.5/lib/rails/command/actions.rb:22:in `require_application!'
        from /usr/local/bundle/gems/railties-7.0.5/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
        from /usr/local/bundle/gems/railties-7.0.5/lib/rails/commands/console/console_command.rb:105:in `perform'
        from /usr/local/bundle/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/railties-7.0.5/lib/rails/command/base.rb:87:in `perform'
        from /usr/local/bundle/gems/railties-7.0.5/lib/rails/command.rb:48:in `invoke'
        from /usr/local/bundle/gems/railties-7.0.5/lib/rails/commands.rb:18:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from bin/rails:4:in `<main>'
```

My versions:
```
$ ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
$ gem -v
3.4.20
$ cat /etc/debian_version 
12.1
```

Any idea what might be wrong?

**Comment by crohr** [comment]
@ankane can easily be replicated with:


```
$ docker run --rm -it ruby:3.2.2 bash -c "gem install tokenizers ; irb -rtokenizers"
Unable to find image 'ruby:3.2.2' locally
3.2.2: Pulling from library/ruby
167b8a53ca45: Pull complete 
b47a222d28fa: Pull complete 
debce5f9f3a9: Pull complete 
1d7ca7cd2e06: Pull complete 
82f3d7e836d3: Pull complete 
8d170f148bf6: Pull complete 
038dc3aed697: Pull complete 
Digest: sha256:eda84591b2b280c825a3416023ed7b08b8a836b9890197db6878522fba165e8b
Status: Downloaded newer image for ruby:3.2.2
Fetching tokenizers-0.4.0-x86_64-linux.gem
Successfully installed tokenizers-0.4.0-x86_64-linux
1 gem installed

A new release of RubyGems is available: 3.4.10 → 3.4.20!
Run `gem update --system 3.4.20` to update your installation.

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Exception(#<NameError: uninitialized constant Tokenizers>))', ext/tokenizers/src/lib.rs:25:97
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': called `Result::unwrap()` on an `Err` value: Error(Exception(#<NameError: uninitialized constant Tokenizers>)) (fatal)
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/bundle/gems/tokenizers-0.4.0-x86_64-linux/lib/tokenizers.rb:3:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:159:in `require'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:159:in `rescue in require'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:39:in `require'
        from /usr/local/lib/ruby/3.2.0/irb/init.rb:423:in `block in load_modules'
        from /usr/local/lib/ruby/3.2.0/irb/init.rb:421:in `each'
        from /usr/local/lib/ruby/3.2.0/irb/init.rb:421:in `load_modules'
        from /usr/local/lib/ruby/3.2.0/irb/init.rb:21:in `setup'
        from /usr/local/lib/ruby/3.2.0/irb.rb:414:in `start'
        from /usr/local/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
        from /usr/local/bin/irb:25:in `load'
        from /usr/local/bin/irb:25:in `<main>'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- tokenizers (LoadError)
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/lib/ruby/3.2.0/irb/init.rb:423:in `block in load_modules'
        from /usr/local/lib/ruby/3.2.0/irb/init.rb:421:in `each'
        from /usr/local/lib/ruby/3.2.0/irb/init.rb:421:in `load_modules'
        from /usr/local/lib/ruby/3.2.0/irb/init.rb:21:in `setup'
        from /usr/local/lib/ruby/3.2.0/irb.rb:414:in `start'
        from /usr/local/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
        from /usr/local/bin/irb:25:in `load'
        from /usr/local/bin/irb:25:in `<main>'
```

**Comment by crohr** [comment]
@ankane thanks a lot, will test as soon as the release is pushed

**Comment by ankane** [comment]
Should be good now

**Comment by crohr** [comment]
@ankane I can confirm it works now, thanks!
